import type { CategoryIconName } from '@/shared/ui';

export const ICON_PRESETS: CategoryIconName[] = [
  'Wallet',
  'Briefcase',
  'Gift',
  'TrendingUp',
  'PartyPopper',
  'Laptop',
  'Sparkles',
  'Landmark',
  'ShoppingCart',
  'UtensilsCrossed',
  'Coffee',
  'Home',
  'Lightbulb',
  'Bus',
  'Car',
  'Plane',
  'Fuel',
  'Pill',
  'HeartPulse',
  'Gamepad2',
  'Film',
  'Music',
  'BookOpen',
  'ShoppingBag',
  'Shirt',
  'RefreshCw',
  'Smartphone',
  'PawPrint',
  'Baby',
  'GraduationCap',
  'Dumbbell',
  'Camera',
  'MoreHorizontal',
];

export const COLOR_PRESETS = [
  '#3DFFB4',
  '#00D4FF',
  '#0057FF',
  '#C2A0FF',
  '#FF9FD1',
  '#FF6BA3',
  '#E4005B',
  '#FFB86B',
  '#FFC857',
  '#FFE066',
  '#7CF6A7',
  '#00A356',
  '#64FFE1',
  '#9FD8FF',
  '#B6FFF9',
  '#C8D4FF',
];
